### ISSUE TITLE
TODO Set 1: Movment!

### ISSUE THREAD

**Issue by SchoolMadeMeMakeGithub** [Ginph/Jovo-s-Slam-Town#4]
- [x] **Wall Jumping:**(There is a small problem but it's easy to fix)
- [x] Detecting when player is touching a wall
- [x] Wall Sliding State
- [x] The actual jumping part
- [x] Sprite and Animations

- [x] **Platforms:**
- [x] Advance Collision
- [x] Falling Through
- [ ] Sprites and Animations(I'm going to wait to before I do this one) 
- [x] Assing a layer to each player at start of game(It's kinda working)

- [x] **Polish**
- [x] New Walking Sprite(He is missing arms but like I said before, I'm going to do it later.)
- [x] Add speed limit to fast fall(I did it, though it makes the game less fun)

**Comment by SchoolMadeMeMakeGithub** [comment]
I spent yesterday adding walljumping. It's not perfect but it really makes the game more fun to play.

**Comment by SchoolMadeMeMakeGithub** [comment]
Working Platforms are done!

**Comment by SchoolMadeMeMakeGithub** [comment]
--> #5
